version: '3.8'
services:
  app-development:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: "infnet-guia-website-development"
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  database:
    extends:
      file: docker-compose.database.yaml
      service: database      
volumes:
  mysql_data: