version: '3.8'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "infnet-guia-website"
    stdin_open: true
    ports:
      - 3000:3000
  database:
    extends:
      file: docker-compose.database.yaml
      service: database
volumes:
  mysql_data: